# INFO: THIS IS THE PROPER CONFIGS FOR DEPLOYMENT!

api:
  dashboard: true
  insecure: true
  debug: false

log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: yuchanandrew@gmail.com
      storage: ./acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory #prod
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory #staging
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
        delayBeforeCheck: 10
